# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install uv
      - pip install -U uv
    post_install:
      # Export dependencies and install into ReadTheDocs virtualenv
      - uv export --frozen --all-groups --no-hashes -o requirements.txt
      - pip install -r requirements.txt
    post_build:
      # Build and publish the agent skill bundle into the rendered docs output.
      - USE_UV_RUN=0 ./scripts/publish-skill-well-known.sh

sphinx:
  configuration: docs/conf.py
