# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install PDM
      - pip install -U pdm
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH pdm install -G:all

sphinx:
  configuration: docs/conf.py
