# Generated by Django 4.2.11 on 2024-04-04 10:07
import django.contrib.postgres.operations as postgres_operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        postgres_operations.CITextExtension(),
    ]
