# Generated by Django 5.0.6 on 2024-09-02 09:57

import alliance_platform.storage.fields.async_file
from django.db import migrations
from django.db import models
import django.db.models.deletion

import test_alliance_platform_storage.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsyncFileTestParentModel",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
            ],
            options={
                "db_table": "test_alliance_platform_storage_async_file_test_parent_model",
            },
        ),
        migrations.CreateModel(
            name="AsyncFileTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "file1",
                    alliance_platform.storage.fields.async_file.AsyncFileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        storage=test_alliance_platform_storage.storage.DummyStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "image_with_dims",
                    alliance_platform.storage.fields.async_file.AsyncImageField(
                        blank=True,
                        height_field="image_height",
                        max_length=500,
                        null=True,
                        storage=test_alliance_platform_storage.storage.DummyStorage(),
                        upload_to="",
                        width_field="image_width",
                    ),
                ),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                (
                    "image_no_dims",
                    alliance_platform.storage.fields.async_file.AsyncImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        storage=test_alliance_platform_storage.storage.DummyStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="test_alliance_platform_storage.asyncfiletestparentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "test_alliance_platform_storage_async_file_test_model",
            },
        ),
    ]
