# Generated by Django 2.2.19 on 2021-03-02 23:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("alliance_platform_storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctempfile",
            name="error",
            field=models.TextField(null=True),
        ),
    ]
