# Generated by Django 3.2.13 on 2022-06-23 09:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("alliance_platform_storage", "0002_asynctempfile_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctempfile",
            name="original_filename",
            field=models.TextField(),
        ),
    ]
