# Generated by Django 4.2.4 on 2023-08-14 04:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("alliance_platform_storage", "0003_alter_asynctempfile_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctempfile",
            name="moved_to_location",
            field=models.TextField(blank=True),
        ),
    ]
