from functools import lru_cache
import json
from json import JSONDecodeError
import logging
from pathlib import Path
import re
from typing import Any
import warnings

from alliance_platform.core.settings import ap_core_settings
from allianceutils.middleware import CurrentRequestMiddleware
from django.http import HttpRequest

from ..settings import ap_frontend_settings
from .base import BaseBundler
from .vite import ViteBundler

logger = logging.getLogger("alliance_platform.frontend")


def resolve_vanilla_extract_cache_names(bundler: ViteBundler, filename: Path | str):
    cache_name = re.sub(r"[/.]", "_", str(filename))
    if bundler.is_development():
        cache_fn = ap_core_settings.CACHE_DIR / f"vanilla-extract-integration/{cache_name}.json"
        return cache_fn, filename
    asset = bundler.build_manifest.get_asset(filename)
    if not asset.vanilla_extract_mapping_file:
        raise ValueError(
            f"Asset '{filename}' has no 'vanillaExtractMappingFile' entry in Vite manifest. "
            "Ensure @alliancesoftware/vite-plugin-django-vanilla-extract is enabled and rebuild assets."
        )
    return ap_frontend_settings.PRODUCTION_DIR / asset.vanilla_extract_mapping_file, None


class VanillaExtractClassMapping:
    """Class that stores class mappings for a Vanilla Extract file

    The mappings are read from a JSON file written by the ``@alliancesoftware/vite-plugin-django-vanilla-extract`` plugin.

    If a class is referenced but does not exist a warning will be logged.

    In dev this triggers a request to the bundler to write the mappings if they don't exist. It also stores the import script
    filename so that it can be included in the template via ViteCssEmbed
    """

    #: Mapping of class names to their hashed names (strings for plain styles, dicts for recipes)
    mapping: dict[str, str | Any] | None
    bundler: BaseBundler
    cache_filename: Path

    _last_request: HttpRequest | None

    def __init__(self, bundler: BaseBundler, filename: Path):
        self._last_request = None
        self.filename = filename
        self.bundler = bundler
        self.cache_filename, self._import_script_filename = resolve_vanilla_extract_cache_names(
            bundler, self.filename
        )
        self._create_mapping()

    @property
    def import_script_filename(self):
        """Only set in dev mode. This is a typescript file generated by ``@alliancesoftware/vite-plugin-django-vanilla-extract`` that imports the css and sets up HMR"""
        self._check_mapping()
        return self._import_script_filename

    _last_map_load_request = None

    def _should_log_mapping_warning(self):
        current_request = CurrentRequestMiddleware.get_request()
        if not self._last_map_load_request:
            self._last_map_load_request = current_request
            return False
        if self._last_map_load_request == current_request:
            return False
        self._last_map_load_request = current_request
        return True

    def _create_mapping(self):
        cache_fn = self.cache_filename
        if not cache_fn.exists():
            self.mapping = None
            # This is expected before the files have been processed the first time. Once the css file is requested from
            # the frontend, the mappings should be rewritten and a reload performed automatically.
            if self._should_log_mapping_warning():
                warnings.warn(
                    f"Mapping for {self.filename} was not found in expected location '{cache_fn}'. No class names will be resolved for this tag."
                )
        else:
            self._load_mapping()
        return

    def _load_mapping(self):
        bundler = self.bundler
        cache_fn = self.cache_filename
        try:
            self.mapping = json.loads(cache_fn.read_text())
        except JSONDecodeError:
            if bundler.is_development():
                warnings.warn(
                    f"Failed to parse cache file {cache_fn}. This may be due to reading the file as it's being written to - try refreshing the browser."
                )
            else:
                logger.exception(f"Failed to parse cache file {cache_fn} - check file is valid JSON.")

    def _check_mapping(self):
        """If dev server has been restarted the cache dir will have been cleared.

        This detects such a case and regenerates files."""
        if self.bundler.is_development() and (
            (not self.cache_filename.exists()) or (self.cache_filename.exists() and not self.mapping)
        ):
            self._create_mapping()
        elif (
            self.bundler.is_development()
            and self.cache_filename.exists()
            and self._last_request != CurrentRequestMiddleware.get_request()
        ):
            # This handles the case where the cache file exists but may need to be reloaded. This can happen if the
            # class name mapping existed already, but details changed. For example, if you change:
            # style([class1, class2]) to style([class1]) then the key will exist in both cases, but the value will
            # change from something like '.class1 .class2' to '.class1'. Because of caching this won't be picked up otherwise.
            self._load_mapping()

        self._last_request = CurrentRequestMiddleware.get_request()

    def __getattr__(self, name):
        self._check_mapping()
        if self.mapping is None:
            if self._should_log_mapping_warning():
                warnings.warn(
                    f"Requested class name '{name}' from '{self.filename}' cannot be resolved because the mapping file was not found."
                )
            return ""
        if name not in self.mapping:
            if self._should_log_mapping_warning():
                warnings.warn(
                    f"Requested class name '{name}' from '{self.filename}' does not exist. Known classes are: {', '.join(self.mapping.keys())}"
                )
            return ""

        return self.mapping.get(name)

    def __str__(self):
        return f"VanillaExtractClassMapping({self.mapping})"


@lru_cache()
def resolve_vanilla_extract_class_mapping(bundler: BaseBundler, filename: Path):
    """Resolve the ``VanillaExtractClassMapping`` instance to use for the given filename"""
    return VanillaExtractClassMapping(bundler, filename)
