[tool.pdm]

[project]
name = "alliance-platform-codegen"
dynamic = ["version"]
description = "Alliance Platform Codegen"
authors = [
    {name = "Alliance Software", email = "support@alliancesoftware.com.au"},
]
dependencies = ["alliance-platform-core"]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "BSD-2-Clause"}
include = [
    "alliance_platform/codegen/py.typed",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = ["alliance_platform"]

[tool.pdm.version]
source = "call"
getter = "extract_version:get_version()"

[tool.django-stubs]
django_settings_module = "test_alliance_platform_codegen.settings"

[tool.mypy]
python_version = "3.11"
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
explicit_package_bases = true

