# Generated by Django 2.2.19 on 2021-03-12 10:27

import common_audit.test_common_audit.models
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pghistory", "0003_auto_20201023_1636"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "test_common_audit_payment_method",
            },
        ),
        migrations.CreateModel(
            name="Plaza",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "test_common_audit_plaza",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Grocery"), (2, "Services"), (3, "Department Store"), (0, "Others")],
                        default=common_audit.test_common_audit.models.ShopCategory(0),
                    ),
                ),
                (
                    "payment_methods_accepted",
                    models.ManyToManyField(
                        blank=True, related_name="shops", to="test_common_audit.PaymentMethod"
                    ),
                ),
                (
                    "plaza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="test_common_audit.Plaza"
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_shop",
            },
        ),
        migrations.CreateModel(
            name="ShopAuditEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Grocery"), (2, "Services"), (3, "Department Store"), (0, "Others")],
                        default=common_audit.test_common_audit.models.ShopCategory(0),
                    ),
                ),
                ("id", models.IntegerField()),
                (
                    "payment_methods_accepted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="test_common_audit.Shop",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.ShopAuditEvent",
                    ),
                ),
                (
                    "plaza",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="test_common_audit.Plaza",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_shop_auditevent",
            },
        ),
        migrations.CreateModel(
            name="PlazaAuditEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("id", models.IntegerField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="test_common_audit.Plaza",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.PlazaAuditEvent",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_plaza_auditevent",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodAuditEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("id", models.IntegerField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event",
                        to="test_common_audit.PaymentMethod",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.PaymentMethodAuditEvent",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_payment_method_auditevent",
            },
        ),
    ]
