# Generated by Django 2.2.19 on 2021-03-28 21:46

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0003_auto_20201023_1636"),
        ("test_common_audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "test_common_audit_profile",
            },
        ),
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_common_audit.Profile",
                    ),
                ),
                ("homepage", models.URLField()),
            ],
            options={
                "db_table": "test_common_audit_author_profile",
            },
            bases=("test_common_audit.profile",),
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_common_audit.Profile",
                    ),
                ),
                ("member_id", models.IntegerField()),
            ],
            options={
                "db_table": "test_common_audit_member_profile",
            },
            bases=("test_common_audit.profile",),
        ),
        migrations.CreateModel(
            name="ProfileAuditEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("name", models.CharField(max_length=100)),
                ("id", models.IntegerField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profile_auditevent",
                        to="test_common_audit.Profile",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.ProfileAuditEvent",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_profile_auditevent",
            },
        ),
        migrations.CreateModel(
            name="SuperMemberProfile",
            fields=[
                (
                    "memberprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_common_audit.MemberProfile",
                    ),
                ),
                ("award_points", models.IntegerField()),
            ],
            options={
                "db_table": "test_common_audit_super_member_profile",
            },
            bases=("test_common_audit.memberprofile",),
        ),
        migrations.CreateModel(
            name="MemberProfileAuditEvent",
            fields=[
                (
                    "profile_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        related_query_name="+",
                        serialize=False,
                        to="test_common_audit.Profile",
                    ),
                ),
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("member_id", models.IntegerField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.MemberProfileAuditEvent",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="member_events",
                        to="test_common_audit.MemberProfile",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_member_profile_auditevent",
            },
        ),
        migrations.CreateModel(
            name="AuthorProfileAuditEvent",
            fields=[
                (
                    "profile_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        related_query_name="+",
                        serialize=False,
                        to="test_common_audit.Profile",
                    ),
                ),
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("homepage", models.URLField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.AuthorProfileAuditEvent",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="author_events",
                        to="test_common_audit.AuthorProfile",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_author_profile_auditevent",
            },
        ),
        migrations.CreateModel(
            name="SuperMemberProfileAuditEvent",
            fields=[
                (
                    "memberprofile_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        related_query_name="+",
                        serialize=False,
                        to="test_common_audit.MemberProfile",
                    ),
                ),
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("award_points", models.IntegerField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.Context",
                    ),
                ),
                (
                    "pgh_previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_common_audit.SuperMemberProfileAuditEvent",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="super_member_events",
                        to="test_common_audit.SuperMemberProfile",
                    ),
                ),
            ],
            options={
                "db_table": "test_common_audit_super_member_profile_auditevent",
            },
        ),
    ]
