# Generated by Django 3.2.5 on 2021-07-12 16:39

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "test_common_audit",
            "0002_authorprofile_authorprofileauditevent_memberprofile_memberprofileauditevent_profile_profileauditeven",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorprofileauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="memberprofileauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="paymentmethodauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="plazaauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="profileauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="shopauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="supermemberprofileauditevent",
            options={"default_permissions": ()},
        ),
        migrations.AlterField(
            model_name="authorprofileauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="author_auditevents",
                to="test_common_audit.authorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethodauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auditevent",
                to="test_common_audit.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="plazaauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auditevent",
                to="test_common_audit.plaza",
            ),
        ),
        migrations.AlterField(
            model_name="profileauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profile_auditevents",
                to="test_common_audit.profile",
            ),
        ),
        migrations.AlterField(
            model_name="shopauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auditevent",
                to="test_common_audit.shop",
            ),
        ),
        migrations.AlterField(
            model_name="supermemberprofileauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="super_member_auditevents",
                to="test_common_audit.supermemberprofile",
            ),
        ),
    ]
