# Generated by Django 3.2.7 on 2021-10-07 02:53

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("test_common_audit", "0003_decorator_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethodauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auditevents",
                to="test_common_audit.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="plazaauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auditevents",
                to="test_common_audit.plaza",
            ),
        ),
        migrations.AlterField(
            model_name="shopauditevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="auditevents",
                to="test_common_audit.shop",
            ),
        ),
    ]
