# Generated by Django 3.2.16 on 2022-10-12 00:01

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_common_audit", "0005_triggers"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="paymentmethod",
            name="test_common_audit_paymentmethod_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="paymentmethod",
            name="test_common_audit_paymentmethod_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="paymentmethod",
            name="test_common_audit_paymentmethod_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="plaza",
            name="test_common_audit_plaza_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="plaza",
            name="test_common_audit_plaza_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="plaza",
            name="test_common_audit_plaza_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="test_common_audit_profile_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="test_common_audit_profile_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="profile",
            name="test_common_audit_profile_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shop",
            name="test_common_audit_shop_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shop",
            name="test_common_audit_shop_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shop",
            name="test_common_audit_shop_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="test_common_audit_shop_payment_methods_accepted_auditeventproxy",
            name="test_common_audit_shop_paym49c05c27_m2m_add",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="test_common_audit_shop_payment_methods_accepted_auditeventproxy",
            name="test_common_audit_shop_p49c05c27_m2m_remove",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="paymentmethod",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_paymentmethod_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_payment_method_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."name", NOW(), \'CREATE\', NEW."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="9a5ff6b3509a492863b227e8b5aa0a257fe57ccb",
                    operation="INSERT",
                    pgid="pgtrigger_test_common_audit_paymentmethod_insert_bd358",
                    table="test_common_audit_payment_method",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="paymentmethod",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_paymentmethod_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."name" IS DISTINCT FROM NEW."name")',
                    func='\n                INSERT INTO "test_common_audit_payment_method_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."name", NOW(), \'UPDATE\', NEW."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="cc3b48b973eb7237593377a8f6766ff3acd0a10d",
                    operation="UPDATE",
                    pgid="pgtrigger_test_common_audit_paymentmethod_update_f8de6",
                    table="test_common_audit_payment_method",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="paymentmethod",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_paymentmethod_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_payment_method_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."id", OLD."name", NOW(), \'DELETE\', OLD."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="77056005938c32690f24a93270ba4b0cb3ea41cd",
                    operation="DELETE",
                    pgid="pgtrigger_test_common_audit_paymentmethod_delete_b18b9",
                    table="test_common_audit_payment_method",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plaza",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_plaza_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_plaza_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."name", NOW(), \'CREATE\', NEW."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="15dd33de43a2855803975413445604d807ca554b",
                    operation="INSERT",
                    pgid="pgtrigger_test_common_audit_plaza_insert_1320d",
                    table="test_common_audit_plaza",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plaza",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_plaza_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."name" IS DISTINCT FROM NEW."name")',
                    func='\n                INSERT INTO "test_common_audit_plaza_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."name", NOW(), \'UPDATE\', NEW."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="1fa01f4510d555cf67186c1647f229a72261e9ee",
                    operation="UPDATE",
                    pgid="pgtrigger_test_common_audit_plaza_update_225ee",
                    table="test_common_audit_plaza",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plaza",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_plaza_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_plaza_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."id", OLD."name", NOW(), \'DELETE\', OLD."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="54d4321c8bc813174c3d7b43f95da372185a0394",
                    operation="DELETE",
                    pgid="pgtrigger_test_common_audit_plaza_delete_be5e3",
                    table="test_common_audit_plaza",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_profile_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_profile_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."name", NOW(), \'CREATE\', NEW."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="902f576f69807b23f301affef37159181b82efb8",
                    operation="INSERT",
                    pgid="pgtrigger_test_common_audit_profile_insert_03215",
                    table="test_common_audit_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_profile_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."name" IS DISTINCT FROM NEW."name")',
                    func='\n                INSERT INTO "test_common_audit_profile_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."name", NOW(), \'UPDATE\', NEW."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="d0611f7a3a3c9931a7114ea2b0c844fc0553024e",
                    operation="UPDATE",
                    pgid="pgtrigger_test_common_audit_profile_update_c769c",
                    table="test_common_audit_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="profile",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_profile_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_profile_auditevent"\n                    ("id", "name", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."id", OLD."name", NOW(), \'DELETE\', OLD."id", _pgh_attach_context());\n                RETURN NULL;\n            ',
                    hash="85fa7bf0a8e579a3e7ac9be473c26037804cbe0e",
                    operation="DELETE",
                    pgid="pgtrigger_test_common_audit_profile_delete_39f27",
                    table="test_common_audit_profile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shop",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_shop_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_shop_auditevent"\n                    ("id", "name", "plaza_id", "category", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id", "payment_methods_accepted") VALUES (NEW."id", NEW."name", NEW."plaza_id", NEW."category", NOW(), \'CREATE\', NEW."id", _pgh_attach_context(), (\n                SELECT "payment_methods_accepted"\n                FROM "test_common_audit_shop_auditevent"\n                WHERE pgh_id=(\n                    SELECT max(pgh_id) from test_common_audit_shop_auditevent where pgh_obj_id = NEW."id"\n                    )\n                ));\n                RETURN NULL;\n            ',
                    hash="80d2677bebead638ceb305622667245755cb0f27",
                    operation="INSERT",
                    pgid="pgtrigger_test_common_audit_shop_insert_9a42e",
                    table="test_common_audit_shop",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shop",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_shop_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM NEW."id" OR OLD."name" IS DISTINCT FROM NEW."name" OR OLD."plaza_id" IS DISTINCT FROM NEW."plaza_id" OR OLD."category" IS DISTINCT FROM NEW."category")',
                    func='\n                INSERT INTO "test_common_audit_shop_auditevent"\n                    ("id", "name", "plaza_id", "category", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id", "payment_methods_accepted") VALUES (NEW."id", NEW."name", NEW."plaza_id", NEW."category", NOW(), \'UPDATE\', NEW."id", _pgh_attach_context(), (\n                SELECT "payment_methods_accepted"\n                FROM "test_common_audit_shop_auditevent"\n                WHERE pgh_id=(\n                    SELECT max(pgh_id) from test_common_audit_shop_auditevent where pgh_obj_id = NEW."id"\n                    )\n                ));\n                RETURN NULL;\n            ',
                    hash="4176942e8883d278ea97561aafd8b74bba02e889",
                    operation="UPDATE",
                    pgid="pgtrigger_test_common_audit_shop_update_15b7b",
                    table="test_common_audit_shop",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shop",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_shop_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                INSERT INTO "test_common_audit_shop_auditevent"\n                    ("id", "name", "plaza_id", "category", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id", "payment_methods_accepted") VALUES (OLD."id", OLD."name", OLD."plaza_id", OLD."category", NOW(), \'DELETE\', OLD."id", _pgh_attach_context(), (\n                SELECT "payment_methods_accepted"\n                FROM "test_common_audit_shop_auditevent"\n                WHERE pgh_id=(\n                    SELECT max(pgh_id) from test_common_audit_shop_auditevent where pgh_obj_id = OLD."id"\n                    )\n                ));\n                RETURN NULL;\n            ',
                    hash="f0e9b6ea6ddbc7f9d76656aeaef467f606329574",
                    operation="DELETE",
                    pgid="pgtrigger_test_common_audit_shop_delete_d2265",
                    table="test_common_audit_shop",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="test_common_audit_shop_payment_methods_accepted_auditeventproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_shop_paym49c05c27_m2m_add",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                        INSERT INTO "test_common_audit_shop_auditevent" ("id", "name", "plaza_id", "category", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id", "payment_methods_accepted")\n                            SELECT "id", "name", "plaza_id", "category", NOW(), \'UPDATE\', NEW."shop_id", _pgh_attach_context(), (\n                                SELECT array_agg("paymentmethod_id")\n                                FROM test_common_audit_shop_payment_methods_accepted\n                                WHERE shop_id=NEW."shop_id"\n                            )\n                            FROM "test_common_audit_shop_auditevent"\n                            WHERE pgh_obj_id=NEW."shop_id"\n                            ORDER BY pgh_id DESC\n                            LIMIT 1;\n                        RETURN NULL;\n                    ',
                    hash="89c4c516d36bb1ef46e61c5a2080a61eead8125b",
                    operation="INSERT",
                    pgid="pgtrigger_test_common_audit_shop_paym49c05c27_m2m_add_0112b",
                    table="test_common_audit_shop_payment_methods_accepted",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="test_common_audit_shop_payment_methods_accepted_auditeventproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="test_common_audit_shop_p49c05c27_m2m_remove",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n                        INSERT INTO "test_common_audit_shop_auditevent" ("id", "name", "plaza_id", "category", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id", "payment_methods_accepted")\n                            SELECT "id", "name", "plaza_id", "category", NOW(), \'UPDATE\', OLD."shop_id", _pgh_attach_context(), (\n                                SELECT array_agg("paymentmethod_id")\n                                FROM test_common_audit_shop_payment_methods_accepted\n                                WHERE shop_id=OLD."shop_id"\n                            )\n                            FROM "test_common_audit_shop_auditevent"\n                            WHERE pgh_obj_id=OLD."shop_id"\n                            ORDER BY pgh_id DESC\n                            LIMIT 1;\n                        RETURN NULL;\n                    ',
                    hash="bbf669e7d26a06c88e8f0e815a8648f8d57d0ee8",
                    operation="DELETE",
                    pgid="pgtrigger_test_common_audit_shop_p49c05c27_m2m_remove_7903d",
                    table="test_common_audit_shop_payment_methods_accepted",
                    when="AFTER",
                ),
            ),
        ),
    ]
