#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

OUTPUT_ROOT="${OUTPUT_ROOT:-$REPO_ROOT/_docs-build/skill-md}"
SKILL_GENERATED_ROOT="${SKILL_GENERATED_ROOT:-$REPO_ROOT/skills/alliance-platform-docs/references/generated}"
SPHINX_SOURCE_DIR="${SPHINX_SOURCE_DIR:-$REPO_ROOT/docs}"
USE_UV_RUN="${USE_UV_RUN:-1}"

PROJECTS=(
    core
    frontend
    codegen
    storage
    audit
    ui
    pdf
    server-choices
    ordered-model
)

strip_package_docs_sidebar() {
    local markdown_file="$1"
    local tmp_file="${markdown_file}.tmp"
    awk '
        /^# Package Docs$/ {
            skip = 1
            next
        }
        skip != 1 {
            print
        }
    ' "$markdown_file" >"$tmp_file"
    mv "$tmp_file" "$markdown_file"
}

echo "Building markdown docs into $OUTPUT_ROOT"
rm -rf "$OUTPUT_ROOT"
mkdir -p "$OUTPUT_ROOT"

echo "Syncing generated markdown into $SKILL_GENERATED_ROOT"
rm -rf "$SKILL_GENERATED_ROOT"
mkdir -p "$SKILL_GENERATED_ROOT"

for project in "${PROJECTS[@]}"; do
    build_dir="$OUTPUT_ROOT/$project"
    echo "  - $project"
    if [[ "$USE_UV_RUN" == "1" ]]; then
        LC_ALL=C LANG=C READTHEDOCS=True READTHEDOCS_VERSION=latest PROJECT="$project" \
            uv run sphinx-build -b markdown "$SPHINX_SOURCE_DIR" "$build_dir"
    else
        LC_ALL=C LANG=C READTHEDOCS=True READTHEDOCS_VERSION=latest PROJECT="$project" \
            sphinx-build -b markdown "$SPHINX_SOURCE_DIR" "$build_dir"
    fi
    find "$build_dir" -type f ! -name "*.md" -delete
    find "$build_dir" -type d -empty -delete
    while IFS= read -r -d '' markdown_file; do
        strip_package_docs_sidebar "$markdown_file"
    done < <(find "$build_dir" -type f -name "*.md" -print0)
    cp -R "$build_dir" "$SKILL_GENERATED_ROOT/$project"
done

cat >"$SKILL_GENERATED_ROOT/README.md" <<'EOF'
# Generated Alliance Platform Docs

This directory is generated by `scripts/build-skill-docs.sh`.

- Source format: reStructuredText in `packages/*/docs/*.rst`
- Build system: Sphinx multiproject (`docs/conf.py`)
- Output format: Markdown via `sphinx-markdown-builder`

Project docs are split by package:

- `core/`
- `frontend/`
- `codegen/`
- `storage/`
- `audit/`
- `ui/`
- `pdf/`
- `server-choices/`
- `ordered-model/`
EOF

echo "Done."
