[tool.pdm]

[project]
name = "alliance-platform-storage"
dynamic = ["version"]
description = "Alliance Platform Storage"
authors = [
    {name = "Alliance Software", email = "support@alliancesoftware.com.au"},
]
dependencies = ["alliance-platform-core", "Django>=4.2.11", "django-allianceutils>=4.0"]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "BSD-2-Clause"}
include = [
    "alliance_platform/storage/py.typed",
]
[project.optional-dependencies]
s3 = ["django-storages[s3]"]
azure = ["django-storages[azure]"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = ["alliance_platform"]

[tool.pdm.version]
source = "call"
getter = "extract_version:get_version()"

[tool.django-stubs]
django_settings_module = "test_alliance_platform_storage.settings"

[tool.mypy]
python_version = "3.11"
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
explicit_package_bases = true

[tool.pdm.dev-dependencies]
dev = [
    "-e alliance-platform-core @ file:///${PROJECT_ROOT}/../ap-core",
    "psycopg2",
    "rules",
    "Pillow",
    "djangorestframework"
]

