name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn

      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11
          cache: true

      - name: Create Release Pull Request or Publish to pypi
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pdm run scripts/publish.py

#      - name: Generate notification payload
#        id: notification
#        if: steps.changesets.outputs.published == 'true'
#        run: payload=$(node scripts/release-notifications.mjs '${{ steps.changesets.outputs.publishedPackages }}') && echo ::set-output name=payload::${payload//$'\n'/'%0A'}
#
#      - name: Send a Slack notification if a publish happens
#        if: steps.changesets.outputs.published == 'true'
#        uses: slackapi/slack-github-action@v1.25.0
#        with:
#          # For posting a rich message using Block Kit
#          payload: ${{ steps.notification.outputs.payload }}
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
